### ISSUE TITLE
Cannot redeploy with my code

### ISSUE THREAD

**Issue by skcc75** [connyay/openshift-iojs#4]
I used this cartridge to successfully create an application using `rhc create-app myapp https://raw.githubusercontent.com/connyay/openshift-iojs/master/metadata/manifest.yml`.

However once I commit and push my own code to OpenShift, nothing changes.  I still have default welcome message.

I verified that my code is indeed pushed to OpenShift, my doing fresh `git clone`.

`rhc deploy master -a drive` also doesn't help, although seems to be working fine:

```
rhc deploy master -a drive
Deployment of git ref 'master' in progress for application drive ...
Enter passphrase for C:/Users/Sergiy Kyrylkov/.ssh/id_rsa:
CLIENT_MESSAGE: Stopping node
Building git ref 'master', commit 48d334e
Preparing build for deployment
Deployment id is b1672ecf
Activating deployment
CLIENT_MESSAGE: Starting node using npm start
Success
```

**Comment by connyay** [comment]
So this was kind of interesting, I wonder if this is what was causing you trouble:

```
❯ git commit -am 'change app'
[master d2b8a7d] change app
 1 file changed, 1 insertion(+), 6 deletions(-)
```

```
 ❯ git push
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 308 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: CLIENT_MESSAGE: Stopping node
remote: Building git ref 'master', commit d2b8a7d
remote: /var/lib/openshift/{id}/app-root/runtime/repo/.openshift/action_hooks/build: line 16: syntax error near unexpected token `fi'
remote: /var/lib/openshift/{id}/app-root/runtime/repo/.openshift/action_hooks/build: line 16: `fi'
remote: An error occurred executing 'gear postreceive' (exit code: 2)
remote: Error message: CLIENT_ERROR: Failed to execute action hook 'build' for {id} application kyrylkov
remote: 
remote: For more details about the problem, try running the command again with the '--trace' option.
To ssh://{id}@kyrylkov-connyay.rhcloud.com/~/git/kyrylkov.git/
   1c0c3a5..d2b8a7d  master -> master
```

**Comment by connyay** [comment]
@kyrylkov see this commit: https://github.com/connyay/openshift-iojs/commit/3f1c67d18b4dd9a5288987fc631277551760f4f8

I changed that in my test app and was able to deploy: http://kyrylkov-connyay.rhcloud.com/

**Comment by skcc75** [comment]
@connyay I tried deleting the hook altogether but it didn't help.  Let me try to comment everything out.

**Comment by skcc75** [comment]
@connyay Alright.  Commenting everything out in the hook helped.  However after `npm install` doesn't seem to be called by default.  I un-commented it in the `build` hook:

```
#!/bin/bash

# Below are example commands that I normally run during a build.

# Change home directory (bower puts a lot of cache and tmp directories here)
#HOME=$OPENSHIFT_REPO_DIR
#cd $OPENSHIFT_REPO_DIR

# Cache npm and bower components on main gear
#if [ "$OPENSHIFT_GEAR_UUID" == "$OPENSHIFT_APP_UUID" ]; then
  #mkdir -p "$OPENSHIFT_DATA_DIR"node_modules
  #mkdir -p "$OPENSHIFT_DATA_DIR"bower_components

  #ln -s "$OPENSHIFT_DATA_DIR"node_modules node_modules
  #ln -s "$OPENSHIFT_DATA_DIR"bower_components bower_components
#fi

npm install

# Prune unused node node_modules
#npm prune

#bower install -q
#grunt build
```

and now have the following error:

```
remote: CLIENT_MESSAGE: Stopping node
remote: Repairing links for 1 deployments
remote: Building git ref 'master', commit ab9f381
remote: npm ERR! install Couldn't read dependencies
remote: npm ERR! Linux 2.6.32-504.16.2.el6.x86_64
remote: npm ERR! argv "/var/lib/openshift/559fb6a45973caf3a6000002/io-js/bin/iojs/bin/iojs" "/var/lib/openshift/559fb6a45973caf3a6000002/io-js/bin/iojs/bin/npm" "install"
remote: npm ERR! node v2.3.3
remote: npm ERR! npm  v2.11.3
remote: npm ERR! path /var/lib/openshift/559fb6a45973caf3a6000002/package.json
remote: npm ERR! code ENOPACKAGEJSON
remote: npm ERR! errno -2
remote: npm ERR! syscall open
remote:
remote: npm ERR! package.json ENOENT: no such file or directory, open '/var/lib/openshift/559fb6a45973caf3a6000002/package.json'
remote: npm ERR! package.json This is most likely not a problem with npm itself.
remote: npm ERR! package.json npm can't find a package.json file in your current directory.
remote: npm ERR! Linux 2.6.32-504.16.2.el6.x86_64
remote: npm ERR! argv "/var/lib/openshift/559fb6a45973caf3a6000002/io-js/bin/iojs/bin/iojs" "/var/lib/openshift/559fb6a45973caf3a6000002/io-js/bin/iojs/bin/npm" "install"
remote: npm ERR! node v2.3.3
remote: npm ERR! npm  v2.11.3
remote: npm ERR! path npm-debug.log.b405b02e7a5a145e446d5878ccb43d00
remote: npm ERR! code EACCES
remote: npm ERR! errno -13
remote: npm ERR! syscall open
remote:
remote: npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.b405b02e7a5a145e446d5878ccb43d00'
remote: npm ERR!     at Error (native)
remote: npm ERR!  { [Error: EACCES: permission denied, open 'npm-debug.log.b405b02e7a5a145e446d5878ccb43d00']
remote: npm ERR!   errno: -13,
remote: npm ERR!   code: 'EACCES',
remote: npm ERR!   syscall: 'open',
remote: npm ERR!   path: 'npm-debug.log.b405b02e7a5a145e446d5878ccb43d00' }
remote: npm ERR!
remote: npm ERR! Please try running this command again as root/Administrator.
remote:
remote: npm ERR! Please include the following file with any support request:
remote: npm ERR!     /var/lib/openshift/559fb6a45973caf3a6000002/npm-debug.log
remote: An error occurred executing 'gear postreceive' (exit code: 254)
remote: Error message: CLIENT_ERROR: Failed to execute action hook 'build' for 559fb6a45973caf3a6000002 application drive2
remote:
remote: For more details about the problem, try running the command again with the '--trace' option.

```

**Comment by connyay** [comment]
@kyrylkov Check out my express example here: https://github.com/connyay/express-openshift-iojs

Just pushed that here: http://kyrylkov-connyay.rhcloud.com/ and all seems well.

[The build hook](https://github.com/connyay/express-openshift-iojs/blob/master/.openshift/action_hooks/build) is important with my cartridges :grin:

**Comment by skcc75** [comment]
@connyay Alright.  Got a little bit further this time.  Any idea what this is?

```
[http] Listening on port: 80
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:814:11)
    at exports._exceptionWithHostPort (util.js:837:20)
    at Server._listen2 (net.js:1205:19)
    at listen (net.js:1254:10)
    at Server.listen (net.js:1344:5)
    at EventEmitter.listen (/var/lib/openshift/559fb6a45973caf3a6000002/app-root/data/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/var/lib/openshift/559fb6a45973caf3a6000002/app-root/runtime/repo/server.js:24:5)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
    at node.js:948:3
error: Forever detected script exited with code: 1
```

**Comment by connyay** [comment]
@kyrylkov 
https://github.com/connyay/express-openshift-iojs/blob/master/app.js#L6-L7

**Comment by skcc75** [comment]
@connyay Thanks, I totally missed this part, moving from Heroku.  

Works perfectly now.

**Comment by connyay** [comment]
Glad to hear it

:beers:

**Comment by probins** [comment]
I'd suggest adding a link to the express example from the readme. I just had similar issues with restify, but all ran fine once I'd tweaked the build script so node_modules get installed in the right place.

**Comment by connyay** [comment]
@probins Link added in ebd98692265f58c3f207555045a7c1a5ddb381a8

**Comment by probins** [comment]
:+1:
